server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # 모든 경로에 대해 CORS 허용
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: account-service
          uri: http://158.247.198.100:32002
          predicates:
            - Path=/accounts-service/**
        - id: schedule-service
          uri: http://158.247.198.100:32000
          predicates:
            - Path=/schedule/**, /example/**