server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # 모든 경로에 대해 CORS 허용
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: account-service
          uri: http://localhost:8030
          predicates:
            - Path=/**
        - id: schedule-service
          uri: http://localhost:8084
          predicates:
            - Path=/**